CREATE TABLE IF NOT EXISTS registration_statuses
(
    reg_status_id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(50),
    CONSTRAINT pk_reg_status PRIMARY KEY (reg_status_id)
    );