CREATE TABLE IF NOT EXISTS events
(
    event_id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name              VARCHAR(2000)                           NOT NULL,
    description       VARCHAR(7000)                           NOT NULL,
    created_date_time TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    start_date_time   TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    end_date_time     TIMESTAMP WITHOUT TIME ZONE             NOT NULL,
    location          BIGINT                                  NOT NULL,
    owner_id          BIGINT                                  NOT NULL,
    CONSTRAINT pk_event PRIMARY KEY (event_id),
    CONSTRAINT fk_event_location
        FOREIGN KEY (location) REFERENCES locations (location_id)
);