CREATE TABLE IF NOT EXISTS organizers
(
    organizer_id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    user_id             BIGINT                                  NOT NULL,
    event_id            BIGINT                                  NOT NULL,
    organizer_role_id   BIGINT                                  NOT NULL,
    CONSTRAINT      pk_organizer_id PRIMARY KEY (organizer_id),
    CONSTRAINT fk_organizer_event
        FOREIGN KEY (event_id) REFERENCES events (event_id),
    CONSTRAINT fk_organizer_role
        FOREIGN KEY (organizer_role_id) REFERENCES organizer_roles (role_id)
    );